stages:
  - build

rust-latest:
  stage: build
  image: rust:latest
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check
    - cargo build --locked --verbose
    - cargo test --locked --verbose
