stages:
  - build

cache:
  paths:
    - ~/.cargo/registry
    - ~/.cargo/git
    - ./target
  key: ${CI_COMMIT_REF_SLUG}

rust-latest:
  stage: build
  image: rust:latest
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check
    - cargo build --locked --verbose
    - cargo test --locked --verbose
