stages:
  - build

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

cache:
  paths:
    - cargo
    - target
  key: ${CI_COMMIT_REF_SLUG}

rust-latest:
  stage: build
  image: rust:latest
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check
    - cargo build --locked --verbose
    - cargo test --locked --verbose
